package model

import (
	"strings"
	"time"
)

type Role struct {
	ID             int        `gorm:"column:id;primaryKey"`
	Name           string     `gorm:"column:name;size:32;index"`
	Status         int        `gorm:"column:status"`
	IsFilterScopes bool       `gorm:"column:is_filter_scopes"`
	Remark         *string    `gorm:"column:remark;type:text"`
	CreatedTime    time.Time  `gorm:"column:created_time;autoCreateTime"`
	UpdatedTime    *time.Time `gorm:"column:updated_time;autoUpdateTime"`
}

type Menu struct {
	ID          int        `gorm:"column:id;primaryKey"`
	Title       string     `gorm:"column:title;size:64;index"`
	Name        string     `gorm:"column:name;size:64"`
	Path        *string    `gorm:"column:path;size:256"`
	ParentID    *int       `gorm:"column:parent_id;index"`
	Sort        int        `gorm:"column:sort"`
	Icon        *string    `gorm:"column:icon;size:128"`
	Type        int        `gorm:"column:type"`
	Component   *string    `gorm:"column:component;size:256"`
	Perms       *string    `gorm:"column:perms;type:text"`
	Status      int        `gorm:"column:status"`
	Display     int        `gorm:"column:display"`
	Cache       int        `gorm:"column:cache"`
	Link        *string    `gorm:"column:link;size:256"`
	Remark      *string    `gorm:"column:remark;type:text"`
	CreatedTime time.Time  `gorm:"column:created_time;autoCreateTime"`
	UpdatedTime *time.Time `gorm:"column:updated_time;autoUpdateTime"`
}

type Dept struct {
	ID          int        `gorm:"column:id;primaryKey"`
	Name        string     `gorm:"column:name;size:64;index"`
	ParentID    *int       `gorm:"column:parent_id;index"`
	Sort        int        `gorm:"column:sort"`
	Leader      *string    `gorm:"column:leader;size:64"`
	Phone       *string    `gorm:"column:phone;size:32"`
	Email       *string    `gorm:"column:email;size:256"`
	Status      int        `gorm:"column:status"`
	Deleted     int        `gorm:"column:deleted;index"`
	CreatedTime time.Time  `gorm:"column:created_time;autoCreateTime"`
	UpdatedTime *time.Time `gorm:"column:updated_time;autoUpdateTime"`
	DeletedTime *time.Time `gorm:"column:deleted_time;index"`
}

type DataRule struct {
	ID          int        `gorm:"column:id;primaryKey"`
	Name        string     `gorm:"column:name;size:64;index"`
	Model       string     `gorm:"column:model;size:64"`
	Column      string     `gorm:"column:column;size:64"`
	Operator    int        `gorm:"column:operator"`
	Expression  int        `gorm:"column:expression"`
	Value       string     `gorm:"column:value;size:256"`
	CreatedTime time.Time  `gorm:"column:created_time;autoCreateTime"`
	UpdatedTime *time.Time `gorm:"column:updated_time;autoUpdateTime"`
}

type DataScope struct {
	ID          int        `gorm:"column:id;primaryKey"`
	Name        string     `gorm:"column:name;size:64;index"`
	Status      int        `gorm:"column:status"`
	CreatedTime time.Time  `gorm:"column:created_time;autoCreateTime"`
	UpdatedTime *time.Time `gorm:"column:updated_time;autoUpdateTime"`
}

func (Role) TableName() string {
	return "sys_role"
}

func (Menu) TableName() string {
	return "sys_menu"
}

func (Dept) TableName() string {
	return "sys_dept"
}

func (DataRule) TableName() string {
	return "sys_data_rule"
}

func (DataScope) TableName() string {
	return "sys_data_scope"
}

type Seed struct {
	Users                           []User
	UserPasswordHistories           []UserPasswordHistory
	Roles                           []Role
	Menus                           []Menu
	Depts                           []Dept
	DataRules                       []DataRule
	DataScopes                      []DataScope
	DataRuleModelTemplateVariables  []DataRuleTemplateVariable
	DataRuleColumnTemplateVariables []DataRuleColumn
	DataRuleValueTemplateVariables  []DataRuleTemplateVariable
	DataRuleModels                  []DataRuleModelMetadata
	Plugins                         []Plugin
	LoginLogs                       []LoginLog
	OperaLogs                       []OperaLog
	Sessions                        []Session
	UserRoles                       map[int][]int
	RoleMenus                       map[int][]int
	RoleScopes                      map[int][]int
	ScopeRules                      map[int][]int
}

func SeedData() Seed {
	ptr := func(value string) *string {
		return &value
	}
	intPtr := func(value int) *int {
		return &value
	}
	dashboardPath := "/dashboard"
	dashboardIcon := "ant-design:dashboard-outlined"
	created := seedTime()
	headquartersName := "总部"
	country := "中国"
	region := "上海"
	city := "上海"
	userAgent := "fba-go contract"
	browser := "Chrome"
	osName := "macOS"
	device := "Desktop"
	operaUsername := "admin"
	operaMsg := "请求成功"
	adminPerms := strings.Join([]string{
		"sys:user:del",
		"sys:role:add",
		"sys:role:edit",
		"sys:role:menu:edit",
		"sys:role:del",
		"sys:menu:add",
		"sys:menu:edit",
		"sys:menu:del",
		"data:rule:add",
		"data:rule:edit",
		"data:rule:del",
		"data:scope:add",
		"data:scope:edit",
		"data:scope:rule:edit",
		"data:scope:del",
		"sys:file:upload",
		"log:login:del",
		"log:login:clear",
		"log:opera:del",
		"log:opera:clear",
		"sys:config:add",
		"sys:config:edit",
		"sys.config.edits",
		"sys:config:del",
		"dict:type:add",
		"dict:type:edit",
		"dict:type:del",
		"dict:data:add",
		"dict:data:edit",
		"dict:data:del",
		"sys:notice:add",
		"sys:notice:edit",
		"sys:notice:del",
		"sys:task:revoke",
		"sys:task:del",
		"sys:task:add",
		"sys:task:edit",
		"sys:task:exec",
	}, ",")
	menus := []Menu{
		{
			ID:          1,
			Title:       "page.dashboard.title",
			Name:        "Dashboard",
			Path:        &dashboardPath,
			Sort:        0,
			Icon:        &dashboardIcon,
			Type:        0,
			Perms:       &adminPerms,
			Status:      1,
			Display:     1,
			Cache:       1,
			CreatedTime: created,
		},
		{
			ID:          2,
			Title:       "page.dashboard.analytics",
			Name:        "Analytics",
			Path:        ptr("/analytics"),
			ParentID:    intPtr(1),
			Sort:        0,
			Icon:        ptr("lucide:area-chart"),
			Type:        1,
			Component:   ptr("/dashboard/analytics/index"),
			Status:      1,
			Display:     1,
			Cache:       1,
			Link:        ptr(""),
			CreatedTime: created,
		},
		{
			ID:          3,
			Title:       "page.dashboard.workspace",
			Name:        "Workspace",
			Path:        ptr("/workspace"),
			ParentID:    intPtr(1),
			Sort:        1,
			Icon:        ptr("carbon:workspace"),
			Type:        1,
			Component:   ptr("/dashboard/workspace/index"),
			Status:      1,
			Display:     1,
			Cache:       1,
			Link:        ptr(""),
			CreatedTime: created,
		},
		{
			ID:          4,
			Title:       "page.menu.system",
			Name:        "System",
			Path:        ptr("/system"),
			Sort:        1,
			Icon:        ptr("eos-icons:admin"),
			Type:        0,
			Status:      1,
			Display:     1,
			Cache:       1,
			Link:        ptr(""),
			CreatedTime: created,
		},
		{
			ID:          5,
			Title:       "page.menu.sysDept",
			Name:        "SysDept",
			Path:        ptr("/system/dept"),
			ParentID:    intPtr(4),
			Sort:        1,
			Icon:        ptr("mingcute:department-line"),
			Type:        1,
			Component:   ptr("/system/dept/index"),
			Status:      1,
			Display:     1,
			Cache:       1,
			Link:        ptr(""),
			CreatedTime: created,
		},
		{
			ID:          6,
			Title:       "新增",
			Name:        "AddSysDept",
			ParentID:    intPtr(5),
			Type:        2,
			Perms:       ptr("sys:dept:add"),
			Status:      1,
			Display:     0,
			Cache:       1,
			Link:        ptr(""),
			CreatedTime: created,
		},
		{
			ID:          7,
			Title:       "修改",
			Name:        "EditSysDept",
			ParentID:    intPtr(5),
			Type:        2,
			Perms:       ptr("sys:dept:edit"),
			Status:      1,
			Display:     0,
			Cache:       1,
			Link:        ptr(""),
			CreatedTime: created,
		},
		{
			ID:          8,
			Title:       "删除",
			Name:        "DeleteSysDept",
			ParentID:    intPtr(5),
			Type:        2,
			Perms:       ptr("sys:dept:del"),
			Status:      1,
			Display:     0,
			Cache:       1,
			Link:        ptr(""),
			CreatedTime: created,
		},
		{
			ID:          9,
			Title:       "page.menu.sysUser",
			Name:        "SysUser",
			Path:        ptr("/system/user"),
			ParentID:    intPtr(4),
			Sort:        2,
			Icon:        ptr("ant-design:user-outlined"),
			Type:        1,
			Component:   ptr("/system/user/index"),
			Status:      1,
			Display:     1,
			Cache:       1,
			Link:        ptr(""),
			CreatedTime: created,
		},
		{
			ID:          10,
			Title:       "删除",
			Name:        "DeleteSysUser",
			ParentID:    intPtr(9),
			Type:        2,
			Perms:       ptr("sys:user:del"),
			Status:      1,
			Display:     0,
			Cache:       1,
			Link:        ptr(""),
			CreatedTime: created,
		},
		{
			ID:          11,
			Title:       "page.menu.sysRole",
			Name:        "SysRole",
			Path:        ptr("/system/role"),
			ParentID:    intPtr(4),
			Sort:        3,
			Icon:        ptr("carbon:user-role"),
			Type:        1,
			Component:   ptr("/system/role/index"),
			Status:      1,
			Display:     1,
			Cache:       1,
			Link:        ptr(""),
			CreatedTime: created,
		},
		{
			ID:          12,
			Title:       "新增",
			Name:        "AddSysRole",
			ParentID:    intPtr(11),
			Type:        2,
			Perms:       ptr("sys:role:add"),
			Status:      1,
			Display:     0,
			Cache:       1,
			Link:        ptr(""),
			CreatedTime: created,
		},
		{
			ID:          13,
			Title:       "修改",
			Name:        "EditSysRole",
			ParentID:    intPtr(11),
			Type:        2,
			Perms:       ptr("sys:role:edit"),
			Status:      1,
			Display:     0,
			Cache:       1,
			Link:        ptr(""),
			CreatedTime: created,
		},
		{
			ID:          14,
			Title:       "修改角色菜单",
			Name:        "EditSysRoleMenu",
			ParentID:    intPtr(11),
			Type:        2,
			Perms:       ptr("sys:role:menu:edit"),
			Status:      1,
			Display:     0,
			Cache:       1,
			Link:        ptr(""),
			CreatedTime: created,
		},
		{
			ID:          15,
			Title:       "修改角色数据范围",
			Name:        "EditSysRoleScope",
			ParentID:    intPtr(11),
			Type:        2,
			Perms:       ptr("sys:role:scope:edit"),
			Status:      1,
			Display:     0,
			Cache:       1,
			Link:        ptr(""),
			CreatedTime: created,
		},
		{
			ID:          16,
			Title:       "删除",
			Name:        "DeleteSysRole",
			ParentID:    intPtr(11),
			Type:        2,
			Perms:       ptr("sys:role:del"),
			Status:      1,
			Display:     0,
			Cache:       1,
			Link:        ptr(""),
			CreatedTime: created,
		},
		{
			ID:          17,
			Title:       "page.menu.sysMenu",
			Name:        "SysMenu",
			Path:        ptr("/system/menu"),
			ParentID:    intPtr(4),
			Sort:        4,
			Icon:        ptr("ant-design:menu-outlined"),
			Type:        1,
			Component:   ptr("/system/menu/index"),
			Status:      1,
			Display:     1,
			Cache:       1,
			Link:        ptr(""),
			CreatedTime: created,
		},
		{
			ID:          18,
			Title:       "新增",
			Name:        "AddSysMenu",
			ParentID:    intPtr(17),
			Type:        2,
			Perms:       ptr("sys:menu:add"),
			Status:      1,
			Display:     0,
			Cache:       1,
			Link:        ptr(""),
			CreatedTime: created,
		},
		{
			ID:          19,
			Title:       "修改",
			Name:        "EditSysMenu",
			ParentID:    intPtr(17),
			Type:        2,
			Perms:       ptr("sys:menu:edit"),
			Status:      1,
			Display:     0,
			Cache:       1,
			Link:        ptr(""),
			CreatedTime: created,
		},
		{
			ID:          20,
			Title:       "删除",
			Name:        "DeleteSysMenu",
			ParentID:    intPtr(17),
			Type:        2,
			Perms:       ptr("sys:menu:del"),
			Status:      1,
			Display:     0,
			Cache:       1,
			Link:        ptr(""),
			CreatedTime: created,
		},
		{
			ID:          21,
			Title:       "page.menu.sysDataPermission",
			Name:        "SysDataPermission",
			Path:        ptr("/system/data-permission"),
			ParentID:    intPtr(4),
			Sort:        5,
			Icon:        ptr("icon-park-outline:permissions"),
			Type:        0,
			Status:      1,
			Display:     1,
			Cache:       1,
			Link:        ptr(""),
			CreatedTime: created,
		},
		{
			ID:          22,
			Title:       "page.menu.sysDataScope",
			Name:        "SysDataScope",
			Path:        ptr("/system/data-scope"),
			ParentID:    intPtr(21),
			Sort:        6,
			Icon:        ptr("cuida:scope-outline"),
			Type:        1,
			Component:   ptr("/system/data-permission/scope/index"),
			Status:      1,
			Display:     1,
			Cache:       1,
			Link:        ptr(""),
			CreatedTime: created,
		},
		{
			ID:          23,
			Title:       "新增",
			Name:        "AddSysDataScope",
			ParentID:    intPtr(22),
			Type:        2,
			Perms:       ptr("data:scope:add"),
			Status:      1,
			Display:     0,
			Cache:       1,
			Link:        ptr(""),
			CreatedTime: created,
		},
		{
			ID:          24,
			Title:       "修改",
			Name:        "EditSysDataScope",
			ParentID:    intPtr(22),
			Type:        2,
			Perms:       ptr("data:scope:edit"),
			Status:      1,
			Display:     0,
			Cache:       1,
			Link:        ptr(""),
			CreatedTime: created,
		},
		{
			ID:          25,
			Title:       "修改数据范围规则",
			Name:        "EditDataScopeRule",
			ParentID:    intPtr(22),
			Type:        2,
			Perms:       ptr("data:scope:rule:edit"),
			Status:      1,
			Display:     0,
			Cache:       1,
			Link:        ptr(""),
			CreatedTime: created,
		},
		{
			ID:          26,
			Title:       "删除",
			Name:        "DeleteSysDataScope",
			ParentID:    intPtr(22),
			Type:        2,
			Perms:       ptr("data:scope:del"),
			Status:      1,
			Display:     0,
			Cache:       1,
			Link:        ptr(""),
			CreatedTime: created,
		},
		{
			ID:          27,
			Title:       "page.menu.sysDataRule",
			Name:        "SysDataRule",
			Path:        ptr("/system/data-rule"),
			ParentID:    intPtr(21),
			Sort:        7,
			Icon:        ptr("material-symbols:rule"),
			Type:        1,
			Component:   ptr("/system/data-permission/rule/index"),
			Status:      1,
			Display:     1,
			Cache:       1,
			Link:        ptr(""),
			CreatedTime: created,
		},
		{
			ID:          28,
			Title:       "新增",
			Name:        "AddSysDataRule",
			ParentID:    intPtr(27),
			Type:        2,
			Perms:       ptr("data:rule:add"),
			Status:      1,
			Display:     0,
			Cache:       1,
			Link:        ptr(""),
			CreatedTime: created,
		},
		{
			ID:          29,
			Title:       "修改",
			Name:        "EditSysDataRule",
			ParentID:    intPtr(27),
			Type:        2,
			Perms:       ptr("data:rule:edit"),
			Status:      1,
			Display:     0,
			Cache:       1,
			Link:        ptr(""),
			CreatedTime: created,
		},
		{
			ID:          30,
			Title:       "删除",
			Name:        "DeleteSysDataRule",
			ParentID:    intPtr(27),
			Type:        2,
			Perms:       ptr("data:rule:del"),
			Status:      1,
			Display:     0,
			Cache:       1,
			Link:        ptr(""),
			CreatedTime: created,
		},
		{
			ID:          31,
			Title:       "page.menu.sysPlugin",
			Name:        "SysPlugin",
			Path:        ptr("/system/plugin"),
			ParentID:    intPtr(4),
			Sort:        8,
			Icon:        ptr("clarity:plugin-line"),
			Type:        1,
			Component:   ptr("/system/plugin/index"),
			Status:      1,
			Display:     1,
			Cache:       1,
			Link:        ptr(""),
			CreatedTime: created,
		},
		{
			ID:          32,
			Title:       "page.menu.scheduler",
			Name:        "Scheduler",
			Path:        ptr("/scheduler"),
			Sort:        2,
			Icon:        ptr("material-symbols:automation"),
			Type:        0,
			Status:      1,
			Display:     1,
			Cache:       1,
			Link:        ptr(""),
			CreatedTime: created,
		},
		{
			ID:          33,
			Title:       "page.menu.schedulerManage",
			Name:        "SchedulerManage",
			Path:        ptr("/scheduler/manage"),
			ParentID:    intPtr(32),
			Sort:        1,
			Icon:        ptr("ix:scheduler"),
			Type:        1,
			Component:   ptr("/scheduler/manage/index"),
			Status:      1,
			Display:     1,
			Cache:       1,
			Link:        ptr(""),
			CreatedTime: created,
		},
		{
			ID:          34,
			Title:       "page.menu.schedulerRecord",
			Name:        "SchedulerRecord",
			Path:        ptr("/scheduler/record"),
			ParentID:    intPtr(32),
			Sort:        2,
			Icon:        ptr("ix:scheduler"),
			Type:        1,
			Component:   ptr("/scheduler/record/index"),
			Status:      1,
			Display:     1,
			Cache:       1,
			Link:        ptr(""),
			CreatedTime: created,
		},
		{
			ID:          35,
			Title:       "page.menu.log",
			Name:        "Log",
			Path:        ptr("/log"),
			Sort:        3,
			Icon:        ptr("carbon:cloud-logging"),
			Type:        0,
			Status:      1,
			Display:     1,
			Cache:       1,
			Link:        ptr(""),
			CreatedTime: created,
		},
		{
			ID:          36,
			Title:       "page.menu.login",
			Name:        "LoginLog",
			Path:        ptr("/log/login"),
			ParentID:    intPtr(35),
			Sort:        1,
			Icon:        ptr("mdi:login"),
			Type:        1,
			Component:   ptr("/log/login/index"),
			Status:      1,
			Display:     1,
			Cache:       1,
			Link:        ptr(""),
			CreatedTime: created,
		},
		{
			ID:          37,
			Title:       "删除",
			Name:        "DeleteLoginLog",
			ParentID:    intPtr(36),
			Type:        2,
			Perms:       ptr("log:login:del"),
			Status:      1,
			Display:     0,
			Cache:       1,
			Link:        ptr(""),
			CreatedTime: created,
		},
		{
			ID:          38,
			Title:       "清空",
			Name:        "EmptyLoginLog",
			ParentID:    intPtr(36),
			Type:        2,
			Perms:       ptr("log:login:clear"),
			Status:      1,
			Display:     0,
			Cache:       1,
			Link:        ptr(""),
			CreatedTime: created,
		},
		{
			ID:          39,
			Title:       "page.menu.opera",
			Name:        "OperaLog",
			Path:        ptr("/log/opera"),
			ParentID:    intPtr(35),
			Sort:        2,
			Icon:        ptr("carbon:operations-record"),
			Type:        1,
			Component:   ptr("/log/opera/index"),
			Status:      1,
			Display:     1,
			Cache:       1,
			Link:        ptr(""),
			CreatedTime: created,
		},
		{
			ID:          40,
			Title:       "删除",
			Name:        "DeleteOperaLog",
			ParentID:    intPtr(39),
			Type:        2,
			Perms:       ptr("log:opera:del"),
			Status:      1,
			Display:     0,
			Cache:       1,
			Link:        ptr(""),
			CreatedTime: created,
		},
		{
			ID:          41,
			Title:       "清空",
			Name:        "EmptyOperaLog",
			ParentID:    intPtr(39),
			Type:        2,
			Perms:       ptr("log:opera:clear"),
			Status:      1,
			Display:     0,
			Cache:       1,
			Link:        ptr(""),
			CreatedTime: created,
		},
		{
			ID:          42,
			Title:       "page.menu.monitor",
			Name:        "Monitor",
			Path:        ptr("/monitor"),
			Sort:        4,
			Icon:        ptr("mdi:monitor-eye"),
			Type:        0,
			Status:      1,
			Display:     1,
			Cache:       1,
			Link:        ptr(""),
			CreatedTime: created,
		},
		{
			ID:          43,
			Title:       "page.menu.online",
			Name:        "Online",
			Path:        ptr("/log/online"),
			ParentID:    intPtr(42),
			Sort:        1,
			Icon:        ptr("wpf:online"),
			Type:        1,
			Component:   ptr("/monitor/online/index"),
			Status:      1,
			Display:     1,
			Cache:       1,
			Link:        ptr(""),
			CreatedTime: created,
		},
		{
			ID:          44,
			Title:       "page.menu.redis",
			Name:        "Redis",
			Path:        ptr("/monitor/redis"),
			ParentID:    intPtr(42),
			Sort:        2,
			Icon:        ptr("devicon:redis"),
			Type:        1,
			Component:   ptr("/monitor/redis/index"),
			Status:      1,
			Display:     1,
			Cache:       1,
			Link:        ptr(""),
			CreatedTime: created,
		},
		{
			ID:          45,
			Title:       "page.menu.server",
			Name:        "Server",
			Path:        ptr("/monitor/server"),
			ParentID:    intPtr(42),
			Sort:        3,
			Icon:        ptr("mdi:server-outline"),
			Type:        1,
			Component:   ptr("/monitor/server/index"),
			Status:      1,
			Display:     1,
			Cache:       1,
			Link:        ptr(""),
			CreatedTime: created,
		},
		{
			ID:          46,
			Title:       "项目",
			Name:        "Project",
			Path:        ptr("/fba"),
			Sort:        5,
			Icon:        ptr("https://wu-clan.github.io/picx-images-hosting/logo/fba.png"),
			Type:        0,
			Status:      1,
			Display:     1,
			Cache:       1,
			Link:        ptr(""),
			CreatedTime: created,
		},
		{
			ID:          47,
			Title:       "文档",
			Name:        "Document",
			Path:        ptr("/fba/document"),
			ParentID:    intPtr(46),
			Sort:        1,
			Icon:        ptr("lucide:book-open-text"),
			Type:        4,
			Component:   ptr("/_core/fallback/iframe.vue"),
			Status:      1,
			Display:     1,
			Cache:       1,
			Link:        ptr("https://fastapi-practices.github.io/fastapi_best_architecture_docs"),
			CreatedTime: created,
		},
		{
			ID:          48,
			Title:       "Github",
			Name:        "Github",
			Path:        ptr("/fba/github"),
			ParentID:    intPtr(46),
			Sort:        2,
			Icon:        ptr("ant-design:github-filled"),
			Type:        4,
			Component:   ptr("/_core/fallback/iframe.vue"),
			Status:      1,
			Display:     1,
			Cache:       1,
			Link:        ptr("https://github.com/fastapi-practices/fastapi-best-architecture"),
			CreatedTime: created,
		},
		{
			ID:          49,
			Title:       "Apifox",
			Name:        "Apifox",
			Path:        ptr("/fba/apifox"),
			ParentID:    intPtr(46),
			Sort:        3,
			Icon:        ptr("simple-icons:apifox"),
			Type:        3,
			Component:   ptr("/_core/fallback/iframe.vue"),
			Status:      1,
			Display:     1,
			Cache:       1,
			Link:        ptr("https://apifox.com/apidoc/shared-28a93f02-730b-4f33-bb5e-4dad92058cc0"),
			CreatedTime: created,
		},
		{
			ID:          50,
			Title:       "page.menu.profile",
			Name:        "Profile",
			Path:        ptr("/profile"),
			Sort:        6,
			Icon:        ptr("ant-design:profile-outlined"),
			Type:        1,
			Component:   ptr("/_core/profile/index"),
			Status:      1,
			Display:     0,
			Cache:       1,
			Link:        ptr(""),
			CreatedTime: created,
		},
		{
			ID:          51,
			Title:       "dict.menu",
			Name:        "PluginDict",
			Path:        ptr("/plugins/dict"),
			ParentID:    intPtr(4),
			Sort:        8,
			Icon:        ptr("fluent-mdl2:dictionary"),
			Type:        1,
			Component:   ptr("/plugins/dict/views/index"),
			Status:      1,
			Display:     1,
			Cache:       1,
			Link:        ptr(""),
			CreatedTime: created,
		},
		{
			ID:          52,
			Title:       "新增类型",
			Name:        "AddDictType",
			ParentID:    intPtr(51),
			Type:        2,
			Perms:       ptr("dict:type:add"),
			Status:      1,
			Display:     0,
			Cache:       1,
			Link:        ptr(""),
			CreatedTime: created,
		},
		{
			ID:          53,
			Title:       "修改类型",
			Name:        "EditDictType",
			ParentID:    intPtr(51),
			Type:        2,
			Perms:       ptr("dict:type:edit"),
			Status:      1,
			Display:     0,
			Cache:       1,
			Link:        ptr(""),
			CreatedTime: created,
		},
		{
			ID:          54,
			Title:       "删除类型",
			Name:        "DeleteDictType",
			ParentID:    intPtr(51),
			Type:        2,
			Perms:       ptr("dict:type:del"),
			Status:      1,
			Display:     0,
			Cache:       1,
			Link:        ptr(""),
			CreatedTime: created,
		},
		{
			ID:          55,
			Title:       "新增数据",
			Name:        "AddDictData",
			ParentID:    intPtr(51),
			Type:        2,
			Perms:       ptr("dict:data:add"),
			Status:      1,
			Display:     0,
			Cache:       1,
			Link:        ptr(""),
			CreatedTime: created,
		},
		{
			ID:          56,
			Title:       "修改数据",
			Name:        "EditDictData",
			ParentID:    intPtr(51),
			Type:        2,
			Perms:       ptr("dict:data:edit"),
			Status:      1,
			Display:     0,
			Cache:       1,
			Link:        ptr(""),
			CreatedTime: created,
		},
		{
			ID:          57,
			Title:       "删除数据",
			Name:        "DeleteDictData",
			ParentID:    intPtr(51),
			Type:        2,
			Perms:       ptr("dict:data:del"),
			Status:      1,
			Display:     0,
			Cache:       1,
			Link:        ptr(""),
			CreatedTime: created,
		},
		{
			ID:          58,
			Title:       "notice.menu",
			Name:        "PluginNotice",
			Path:        ptr("/plugins/notice"),
			ParentID:    intPtr(4),
			Sort:        9,
			Icon:        ptr("fe:notice-push"),
			Type:        1,
			Component:   ptr("/plugins/notice/views/index"),
			Status:      1,
			Display:     1,
			Cache:       1,
			Link:        ptr(""),
			CreatedTime: created,
		},
		{
			ID:          59,
			Title:       "新增",
			Name:        "AddNotice",
			ParentID:    intPtr(58),
			Type:        2,
			Perms:       ptr("sys:notice:add"),
			Status:      1,
			Display:     0,
			Cache:       1,
			Link:        ptr(""),
			CreatedTime: created,
		},
		{
			ID:          60,
			Title:       "修改",
			Name:        "EditNotice",
			ParentID:    intPtr(58),
			Type:        2,
			Perms:       ptr("sys:notice:edit"),
			Status:      1,
			Display:     0,
			Cache:       1,
			Link:        ptr(""),
			CreatedTime: created,
		},
		{
			ID:          61,
			Title:       "删除",
			Name:        "DeleteNotice",
			ParentID:    intPtr(58),
			Type:        2,
			Perms:       ptr("sys:notice:del"),
			Status:      1,
			Display:     0,
			Cache:       1,
			Link:        ptr(""),
			CreatedTime: created,
		},
		{
			ID:          62,
			Title:       "config.menu",
			Name:        "PluginConfig",
			Path:        ptr("/plugins/config"),
			ParentID:    intPtr(4),
			Sort:        7,
			Icon:        ptr("codicon:symbol-parameter"),
			Type:        1,
			Component:   ptr("/plugins/config/views/index"),
			Status:      1,
			Display:     1,
			Cache:       1,
			Link:        ptr(""),
			CreatedTime: created,
		},
		{
			ID:          63,
			Title:       "新增",
			Name:        "AddConfig",
			ParentID:    intPtr(62),
			Type:        2,
			Perms:       ptr("sys:config:add"),
			Status:      1,
			Display:     0,
			Cache:       1,
			Link:        ptr(""),
			CreatedTime: created,
		},
		{
			ID:          64,
			Title:       "修改",
			Name:        "EditConfig",
			ParentID:    intPtr(62),
			Type:        2,
			Perms:       ptr("sys:config:edit"),
			Status:      1,
			Display:     0,
			Cache:       1,
			Link:        ptr(""),
			CreatedTime: created,
		},
		{
			ID:          65,
			Title:       "删除",
			Name:        "DeleteConfig",
			ParentID:    intPtr(62),
			Type:        2,
			Perms:       ptr("sys:config:del"),
			Status:      1,
			Display:     0,
			Cache:       1,
			Link:        ptr(""),
			CreatedTime: created,
		},
		{
			ID:          70,
			Title:       "新增",
			Name:        "AddScheduler",
			ParentID:    intPtr(33),
			Type:        2,
			Perms:       ptr("sys:task:add"),
			Status:      1,
			Display:     0,
			Cache:       1,
			Link:        ptr(""),
			CreatedTime: created,
		},
		{
			ID:          71,
			Title:       "修改",
			Name:        "EditScheduler",
			ParentID:    intPtr(33),
			Type:        2,
			Perms:       ptr("sys:task:edit"),
			Status:      1,
			Display:     0,
			Cache:       1,
			Link:        ptr(""),
			CreatedTime: created,
		},
		{
			ID:          72,
			Title:       "删除",
			Name:        "DeleteScheduler",
			ParentID:    intPtr(33),
			Type:        2,
			Perms:       ptr("sys:task:del"),
			Status:      1,
			Display:     0,
			Cache:       1,
			Link:        ptr(""),
			CreatedTime: created,
		},
		{
			ID:          73,
			Title:       "执行",
			Name:        "ExecuteScheduler",
			ParentID:    intPtr(33),
			Type:        2,
			Perms:       ptr("sys:task:exec"),
			Status:      1,
			Display:     0,
			Cache:       1,
			Link:        ptr(""),
			CreatedTime: created,
		},
		{
			ID:          74,
			Title:       "撤销",
			Name:        "RevokeTask",
			ParentID:    intPtr(34),
			Type:        2,
			Perms:       ptr("sys:task:revoke"),
			Status:      1,
			Display:     0,
			Cache:       1,
			Link:        ptr(""),
			CreatedTime: created,
		},
	}
	return Seed{
		Users: []User{
			{
				ID:                      1,
				UUID:                    "fixture-user",
				DeptID:                  intPtr(1),
				Username:                "admin",
				Nickname:                "Admin",
				Status:                  1,
				IsSuperuser:             true,
				IsStaff:                 true,
				IsMultiLogin:            true,
				JoinTime:                created,
				LastPasswordChangedTime: &created,
			},
		},
		Roles: []Role{
			{
				ID:             1,
				Name:           "admin",
				Status:         1,
				IsFilterScopes: true,
				CreatedTime:    created,
			},
			{
				ID:             2,
				Name:           "viewer",
				Status:         1,
				IsFilterScopes: false,
				CreatedTime:    created,
			},
		},
		Menus: menus,
		Depts: []Dept{
			{
				ID:          1,
				Name:        headquartersName,
				Sort:        0,
				Status:      1,
				Deleted:     0,
				CreatedTime: created,
			},
		},
		DataRules: []DataRule{
			{
				ID:          1,
				Name:        "本人数据",
				Model:       "user",
				Column:      "id",
				Operator:    0,
				Expression:  0,
				Value:       "{{ user_id }}",
				CreatedTime: created,
			},
		},
		DataScopes: []DataScope{
			{
				ID:          1,
				Name:        "本人数据范围",
				Status:      1,
				CreatedTime: created,
			},
		},
		DataRuleModelTemplateVariables: []DataRuleTemplateVariable{
			{Key: "__ALL__", Comment: "所有模型"},
		},
		DataRuleColumnTemplateVariables: []DataRuleColumn{
			{Key: "__dept_id__", Comment: "部门 ID"},
			{Key: "__created_by__", Comment: "创建者"},
		},
		DataRuleValueTemplateVariables: []DataRuleTemplateVariable{
			{Key: "${user_id}", Comment: "当前登录用户 ID"},
			{Key: "${dept_id}", Comment: "当前登录用户部门 ID"},
			{Key: "${now}", Comment: "当前时间"},
		},
		DataRuleModels: []DataRuleModelMetadata{
			{
				Name: "user",
				Columns: []DataRuleColumn{
					{Key: "uuid", Comment: "用户 UUID"},
					{Key: "dept_id", Comment: "部门 ID"},
					{Key: "username", Comment: "用户名"},
					{Key: "nickname", Comment: "昵称"},
					{Key: "status", Comment: "状态"},
					{Key: "is_superuser", Comment: "是否超级管理员"},
					{Key: "is_staff", Comment: "是否管理员"},
					{Key: "is_multi_login", Comment: "是否允许多端登录"},
					{Key: "join_time", Comment: "加入时间"},
					{Key: "last_login_time", Comment: "最后登录时间"},
				},
			},
			{
				Name: "role",
				Columns: []DataRuleColumn{
					{Key: "name", Comment: "角色名称"},
					{Key: "status", Comment: "状态"},
					{Key: "is_filter_scopes", Comment: "是否过滤数据权限"},
					{Key: "remark", Comment: "备注"},
				},
			},
			{
				Name: "menu",
				Columns: []DataRuleColumn{
					{Key: "title", Comment: "菜单标题"},
					{Key: "name", Comment: "路由名称"},
					{Key: "path", Comment: "路由路径"},
					{Key: "parent_id", Comment: "父级 ID"},
					{Key: "type", Comment: "类型"},
					{Key: "component", Comment: "组件"},
					{Key: "perms", Comment: "权限标识"},
					{Key: "status", Comment: "状态"},
					{Key: "display", Comment: "是否显示"},
					{Key: "cache", Comment: "是否缓存"},
				},
			},
			{
				Name: "dept",
				Columns: []DataRuleColumn{
					{Key: "name", Comment: "部门名称"},
					{Key: "parent_id", Comment: "父级 ID"},
					{Key: "leader", Comment: "负责人"},
					{Key: "phone", Comment: "联系电话"},
					{Key: "email", Comment: "邮箱"},
					{Key: "status", Comment: "状态"},
				},
			},
		},
		Plugins: []Plugin{
			{
				ID:          "config",
				Summary:     "参数配置",
				Version:     "0.0.2",
				Description: "System config plugin",
				Author:      "wu-clan",
				Tags:        []string{"other"},
				Database:    []string{"mysql", "postgresql"},
				DependsOn:   []string{"admin"},
				Enabled:     true,
				BuiltIn:     true,
			},
			{
				ID:          "dict",
				Summary:     "数据字典",
				Version:     "0.0.8",
				Description: "Dictionary data plugin",
				Author:      "wu-clan",
				Tags:        []string{"other"},
				Database:    []string{"mysql", "postgresql"},
				DependsOn:   []string{"admin"},
				Enabled:     true,
				BuiltIn:     true,
			},
			{
				ID:          "email",
				Summary:     "电子邮件",
				Version:     "0.0.3",
				Description: "Email captcha plugin",
				Author:      "wu-clan",
				Tags:        []string{"other"},
				Database:    []string{"mysql", "postgresql"},
				Enabled:     true,
				BuiltIn:     true,
			},
			{
				ID:          "notice",
				Summary:     "通知公告",
				Version:     "0.0.2",
				Description: "System notice and announcement plugin",
				Author:      "wu-clan",
				Tags:        []string{"other"},
				Database:    []string{"mysql", "postgresql"},
				DependsOn:   []string{"admin"},
				Enabled:     true,
				BuiltIn:     true,
			},
			{
				ID:          "oauth2",
				Summary:     "OAuth 2.0",
				Version:     "0.0.11",
				Description: "支持 GitHub、Google 等社交平台登录",
				Author:      "wu-clan",
				Tags:        []string{"auth"},
				Database:    []string{"mysql", "postgresql"},
				DependsOn:   []string{"admin"},
				Enabled:     true,
				BuiltIn:     true,
			},
			{
				ID:          "task",
				Summary:     "任务调度",
				Version:     "0.1.0",
				Description: "Task scheduler compatibility plugin",
				Author:      "wu-clan",
				Tags:        []string{"task"},
				Database:    []string{"mysql", "postgresql"},
				DependsOn:   []string{"admin"},
				Enabled:     true,
				BuiltIn:     true,
			},
			{
				ID:          "code_generator",
				Summary:     "代码生成",
				Version:     "0.1.1",
				Description: "Go 版本不实现代码生成插件：AI 时代不再提供动态代码生成业务，仅保留清单标记",
				Author:      "wu-clan",
				Tags:        []string{"other"},
				Database:    []string{"mysql", "postgresql"},
				DependsOn:   []string{"admin"},
				Enabled:     false,
				BuiltIn:     true,
			},
		},
		LoginLogs: []LoginLog{
			{
				ID:          1,
				UserUUID:    "fixture-user",
				Username:    "admin",
				Status:      1,
				IP:          "127.0.0.1",
				Country:     &country,
				Region:      &region,
				City:        &city,
				UserAgent:   &userAgent,
				Browser:     &browser,
				OS:          &osName,
				Device:      &device,
				Msg:         "登录成功",
				LoginTime:   created,
				CreatedTime: created,
			},
		},
		OperaLogs: []OperaLog{
			{
				ID:          1,
				TraceID:     "fixture-trace",
				Username:    &operaUsername,
				Method:      "GET",
				Title:       "List users",
				Path:        "/api/v1/sys/users",
				IP:          "127.0.0.1",
				Country:     &country,
				Region:      &region,
				City:        &city,
				UserAgent:   &userAgent,
				Browser:     &browser,
				OS:          &osName,
				Device:      &device,
				Args:        map[string]any{"page": "1", "size": "20"},
				Status:      1,
				Code:        "200",
				Msg:         &operaMsg,
				CostTime:    1.2,
				OperaTime:   created,
				CreatedTime: created,
			},
		},
		Sessions: []Session{
			{
				ID:            1,
				SessionUUID:   "fixture-session",
				Username:      "admin",
				Nickname:      "Admin",
				IP:            "127.0.0.1",
				OS:            "macOS",
				Browser:       "Chrome",
				Device:        "Desktop",
				Status:        1,
				LastLoginTime: created.Format("2006-01-02 15:04:05"),
				ExpireTime:    created.Add(2 * time.Hour),
			},
		},
		UserRoles:  map[int][]int{1: {1}},
		RoleMenus:  map[int][]int{1: seedMenuIDs(menus)},
		RoleScopes: map[int][]int{},
		ScopeRules: map[int][]int{1: {1}},
	}
}

func seedTime() time.Time {
	return time.Date(2026, 5, 30, 0, 0, 0, 0, time.Local)
}

func seedMenuIDs(menus []Menu) []int {
	ids := make([]int, 0, len(menus))
	for _, menu := range menus {
		ids = append(ids, menu.ID)
	}
	return ids
}
