package model

import "time"

type DictData struct {
	ID          int        `gorm:"column:id;primaryKey"`
	TypeID      int        `gorm:"column:type_id;index"`
	TypeCode    string     `gorm:"column:type_code;size:32;index"`
	Label       string     `gorm:"column:label;size:32"`
	Value       string     `gorm:"column:value;size:32"`
	Color       *string    `gorm:"column:color;size:32"`
	Sort        int        `gorm:"column:sort"`
	Status      int        `gorm:"column:status"`
	Remark      *string    `gorm:"column:remark"`
	CreatedTime time.Time  `gorm:"column:created_time;autoCreateTime"`
	UpdatedTime *time.Time `gorm:"column:updated_time;autoUpdateTime"`
}

func (DictData) TableName() string {
	return "sys_dict_data"
}

func SeedDictData() []DictData {
	created := seedTime()
	ptr := func(value string) *string {
		return &value
	}
	return []DictData{
		{
			ID:          1,
			TypeID:      1,
			TypeCode:    "sys_status",
			Label:       "停用",
			Value:       "0",
			Color:       ptr("red"),
			Sort:        1,
			Status:      1,
			Remark:      ptr("停用状态"),
			CreatedTime: created,
		},
		{
			ID:          2,
			TypeID:      1,
			TypeCode:    "sys_status",
			Label:       "正常",
			Value:       "1",
			Color:       ptr("green"),
			Sort:        2,
			Status:      1,
			Remark:      ptr("正常状态"),
			CreatedTime: created,
		},
		{
			ID:          3,
			TypeID:      2,
			TypeCode:    "sys_choose",
			Label:       "关闭",
			Value:       "false",
			Color:       ptr("error"),
			Sort:        1,
			Status:      1,
			Remark:      ptr("关闭状态"),
			CreatedTime: created,
		},
		{
			ID:          4,
			TypeID:      2,
			TypeCode:    "sys_choose",
			Label:       "开启",
			Value:       "true",
			Color:       ptr("success"),
			Sort:        2,
			Status:      1,
			Remark:      ptr("开启状态"),
			CreatedTime: created,
		},
		{
			ID:          5,
			TypeID:      3,
			TypeCode:    "sys_menu_type",
			Label:       "目录",
			Value:       "0",
			Color:       ptr("orange"),
			Sort:        1,
			Status:      1,
			Remark:      ptr("菜单目录"),
			CreatedTime: created,
		},
		{
			ID:          6,
			TypeID:      3,
			TypeCode:    "sys_menu_type",
			Label:       "菜单",
			Value:       "1",
			Color:       ptr("default"),
			Sort:        2,
			Status:      1,
			Remark:      ptr("普通菜单"),
			CreatedTime: created,
		},
		{
			ID:          7,
			TypeID:      3,
			TypeCode:    "sys_menu_type",
			Label:       "按钮",
			Value:       "2",
			Color:       ptr("processing"),
			Sort:        3,
			Status:      1,
			Remark:      ptr("菜单按钮"),
			CreatedTime: created,
		},
		{
			ID:          8,
			TypeID:      3,
			TypeCode:    "sys_menu_type",
			Label:       "内嵌",
			Value:       "3",
			Color:       ptr("cyan"),
			Sort:        4,
			Status:      1,
			Remark:      ptr("内嵌页面"),
			CreatedTime: created,
		},
		{
			ID:          9,
			TypeID:      3,
			TypeCode:    "sys_menu_type",
			Label:       "外链",
			Value:       "4",
			Color:       ptr("purple"),
			Sort:        5,
			Status:      1,
			Remark:      ptr("外部链接"),
			CreatedTime: created,
		},
		{
			ID:          10,
			TypeID:      4,
			TypeCode:    "sys_login_status",
			Label:       "失败",
			Value:       "0",
			Color:       ptr("error"),
			Sort:        1,
			Status:      1,
			Remark:      ptr("登录失败状态"),
			CreatedTime: created,
		},
		{
			ID:          11,
			TypeID:      4,
			TypeCode:    "sys_login_status",
			Label:       "成功",
			Value:       "1",
			Color:       ptr("success"),
			Sort:        2,
			Status:      1,
			Remark:      ptr("登录成功状态"),
			CreatedTime: created,
		},
		{
			ID:          12,
			TypeID:      5,
			TypeCode:    "sys_data_rule_operator",
			Label:       "AND",
			Value:       "0",
			Color:       ptr("green"),
			Sort:        1,
			Status:      1,
			Remark:      ptr("逻辑 AND 运算符"),
			CreatedTime: created,
		},
		{
			ID:          13,
			TypeID:      5,
			TypeCode:    "sys_data_rule_operator",
			Label:       "OR",
			Value:       "1",
			Color:       ptr("gold"),
			Sort:        2,
			Status:      1,
			Remark:      ptr("逻辑 OR 运算符"),
			CreatedTime: created,
		},
		{
			ID:          14,
			TypeID:      6,
			TypeCode:    "sys_data_rule_expression",
			Label:       "等于(==)",
			Value:       "0",
			Color:       ptr("success"),
			Sort:        1,
			Status:      1,
			Remark:      ptr("等于比较表达式"),
			CreatedTime: created,
		},
		{
			ID:          15,
			TypeID:      6,
			TypeCode:    "sys_data_rule_expression",
			Label:       "不等于(!=)",
			Value:       "1",
			Color:       ptr("error"),
			Sort:        2,
			Status:      1,
			Remark:      ptr("不等于比较表达式"),
			CreatedTime: created,
		},
		{
			ID:          16,
			TypeID:      6,
			TypeCode:    "sys_data_rule_expression",
			Label:       "大于(>)",
			Value:       "2",
			Color:       ptr("magenta"),
			Sort:        3,
			Status:      1,
			Remark:      ptr("大于比较表达式"),
			CreatedTime: created,
		},
		{
			ID:          17,
			TypeID:      6,
			TypeCode:    "sys_data_rule_expression",
			Label:       "大于等于(>=)",
			Value:       "3",
			Color:       ptr("volcano"),
			Sort:        4,
			Status:      1,
			Remark:      ptr("大于等于比较表达式"),
			CreatedTime: created,
		},
		{
			ID:          18,
			TypeID:      6,
			TypeCode:    "sys_data_rule_expression",
			Label:       "小于(<)",
			Value:       "4",
			Color:       ptr("gold"),
			Sort:        5,
			Status:      1,
			Remark:      ptr("小于比较表达式"),
			CreatedTime: created,
		},
		{
			ID:          19,
			TypeID:      6,
			TypeCode:    "sys_data_rule_expression",
			Label:       "小于等于(<=)",
			Value:       "5",
			Color:       ptr("orange"),
			Sort:        6,
			Status:      1,
			Remark:      ptr("小于等于比较表达式"),
			CreatedTime: created,
		},
		{
			ID:          20,
			TypeID:      6,
			TypeCode:    "sys_data_rule_expression",
			Label:       "包含(in)",
			Value:       "6",
			Color:       ptr("purple"),
			Sort:        7,
			Status:      1,
			Remark:      ptr("包含表达式"),
			CreatedTime: created,
		},
		{
			ID:          21,
			TypeID:      6,
			TypeCode:    "sys_data_rule_expression",
			Label:       "不包含(not in)",
			Value:       "7",
			Color:       ptr("error"),
			Sort:        8,
			Status:      1,
			Remark:      ptr("不包含表达式"),
			CreatedTime: created,
		},
		{
			ID:          22,
			TypeID:      7,
			TypeCode:    "sys_frontend_config",
			Label:       "否",
			Value:       "0",
			Color:       ptr("red"),
			Sort:        1,
			Status:      1,
			Remark:      ptr("不是前端参数配置"),
			CreatedTime: created,
		},
		{
			ID:          23,
			TypeID:      7,
			TypeCode:    "sys_frontend_config",
			Label:       "是",
			Value:       "1",
			Color:       ptr("green"),
			Sort:        2,
			Status:      1,
			Remark:      ptr("是前端参数配置"),
			CreatedTime: created,
		},
		{
			ID:          24,
			TypeID:      8,
			TypeCode:    "task_strategy_type",
			Label:       "Interval（间隔）",
			Value:       "0",
			Color:       ptr("cyan"),
			Sort:        1,
			Status:      1,
			Remark:      ptr("时间间隔策略"),
			CreatedTime: created,
		},
		{
			ID:          25,
			TypeID:      8,
			TypeCode:    "task_strategy_type",
			Label:       "Crontab（计划）",
			Value:       "1",
			Color:       ptr("purple"),
			Sort:        2,
			Status:      1,
			Remark:      ptr("时间表达式策略"),
			CreatedTime: created,
		},
		{
			ID:          26,
			TypeID:      9,
			TypeCode:    "task_period_type",
			Label:       "天",
			Value:       "days",
			Color:       ptr("processing"),
			Sort:        1,
			Status:      1,
			Remark:      ptr("定时任务周期类型-天"),
			CreatedTime: created,
		},
		{
			ID:          27,
			TypeID:      9,
			TypeCode:    "task_period_type",
			Label:       "小时",
			Value:       "hours",
			Color:       ptr("magenta"),
			Sort:        2,
			Status:      1,
			Remark:      ptr("定时任务周期类型-小时"),
			CreatedTime: created,
		},
		{
			ID:          28,
			TypeID:      9,
			TypeCode:    "task_period_type",
			Label:       "分钟",
			Value:       "minutes",
			Color:       ptr("volcano"),
			Sort:        3,
			Status:      1,
			Remark:      ptr("定时任务周期类型-分钟"),
			CreatedTime: created,
		},
		{
			ID:          29,
			TypeID:      9,
			TypeCode:    "task_period_type",
			Label:       "秒",
			Value:       "seconds",
			Color:       ptr("gold"),
			Sort:        4,
			Status:      1,
			Remark:      ptr("定时任务周期类型-秒"),
			CreatedTime: created,
		},
		{
			ID:          30,
			TypeID:      9,
			TypeCode:    "task_period_type",
			Label:       "微妙",
			Value:       "microseconds",
			Color:       ptr("warning"),
			Sort:        5,
			Status:      1,
			Remark:      ptr("定时任务周期类型-微妙"),
			CreatedTime: created,
		},
		{
			ID:          31,
			TypeID:      10,
			TypeCode:    "notice",
			Label:       "通知",
			Value:       "0",
			Color:       ptr("magenta"),
			Sort:        1,
			Status:      1,
			Remark:      ptr("通知类型"),
			CreatedTime: created,
		},
		{
			ID:          32,
			TypeID:      10,
			TypeCode:    "notice",
			Label:       "公告",
			Value:       "1",
			Color:       ptr("purple"),
			Sort:        2,
			Status:      1,
			Remark:      ptr("公告类型"),
			CreatedTime: created,
		},
		{
			ID:          33,
			TypeID:      11,
			TypeCode:    "user_online_status",
			Label:       "离线",
			Value:       "0",
			Color:       ptr("warning"),
			Sort:        1,
			Status:      1,
			Remark:      ptr("用户离线状态"),
			CreatedTime: created,
		},
		{
			ID:          34,
			TypeID:      11,
			TypeCode:    "user_online_status",
			Label:       "在线",
			Value:       "1",
			Color:       ptr("success"),
			Sort:        2,
			Status:      1,
			Remark:      ptr("用户在线状态"),
			CreatedTime: created,
		},
		{
			ID:          35,
			TypeID:      12,
			TypeCode:    "sys_plugin_type",
			Label:       "压缩包",
			Value:       "0",
			Color:       ptr("gold"),
			Sort:        1,
			Status:      1,
			Remark:      ptr("插件类型-压缩包"),
			CreatedTime: created,
		},
		{
			ID:          36,
			TypeID:      12,
			TypeCode:    "sys_plugin_type",
			Label:       "GIT",
			Value:       "1",
			Color:       ptr("processing"),
			Sort:        2,
			Status:      1,
			Remark:      ptr("插件类型-GIT"),
			CreatedTime: created,
		},
	}
}
